name: Test, build and coverage
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  test-matrix:
    strategy:
      matrix:
        go-version: ['1.19', '1.20']
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build binary
        run: make build
      - name: Run tests
        run: make test
      - name: Send code coverage
        uses: codecov/codecov-action@v3
